travis:
  secure:
    BINSTAR_TOKEN: DJG1oFOnWzVBYftiZX0v3qlBfJNu/F83a0Bm76Za/AOxxHPP1So4WNV+pR2Td6yRplhulsPFeTU9zpoUg8IJltMcvkTKsy0/Auwz1slnRISmd+m2CK85+35IqViIaNTS5oWiE3shlBaPQKjWlVOqtX0x6Mz4Ydpb5rq9ReQ8Jq/tMM+pmGzwql5f+nZzqDir0wfijGMfs9C2Cb2ugRo0dlmb14bTa3p2dIGSzN0rlszVXDfosHoJwC3G129WUwpOgVcbCFsAvKGjU8ZZugB8YzODOlA85vuWFvxLijOoPfzT9VbWkl9CqR6aHUm5Aoszm2cf9fnbzaWUDPkdBKwacMBecCdLGe4csRWBW/ZQ4m5GIhvJRVJcFJplAIP514Ge7OgvA/j99GoRxea3tOhyK6X6Yr/v99y32uTEL1BJT175o/Jo0GP9+gR2bM/GtFx6w29AAl3oxYOsStR+fDcJYQP6uFbYort27muAhM/YYoK7Q2aE75H6R/WBdj5h9uDnXoQzuHqpMFOB8i0jBH8mrttBt2IpayMjRgvWa8sDVAtA3325DyKRleZ2rJh4QGK/1Yd19lXiSMi9y6DbNSNxpbyf6FJUieSy0kOSQwTcDnPoZJm1htC1IBNGS0XPxYfIm77Yw272PuEUEldZidEihp9fQV9bvNTS7CTi1MDLVD8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
